import type { CartographManifest } from "./cartographJson.js";

export function buildAgentsMd(manifest: CartographManifest, topN = 15): string {
  const topFiles = [...manifest.nodes].sort((a, b) => b.centrality - a.centrality).slice(0, topN);

  const lines: string[] = [];
  lines.push("# AGENTS.md");
  lines.push("");
  lines.push(
    `Generated by Cartograph on ${manifest.generated_at}. ${manifest.nodes.length} files, ${manifest.edges.length} import edges, ${manifest.clusters.length} clusters.`,
  );
  lines.push("");
  lines.push("## Load-bearing files (by import centrality)");
  lines.push("");
  for (const f of topFiles) {
    lines.push(`- \`${f.id}\` — cluster ${f.cluster}, ${f.loc} LOC, centrality ${f.centrality.toFixed(4)}`);
  }
  lines.push("");
  lines.push("## Subsystem map");
  lines.push("");
  for (const cluster of manifest.clusters) {
    lines.push(`### Cluster ${cluster.id} (${cluster.files.length} files)`);
    for (const file of cluster.files.slice(0, 20)) lines.push(`- \`${file}\``);
    if (cluster.files.length > 20) lines.push(`- ...and ${cluster.files.length - 20} more`);
    lines.push("");
  }
  return lines.join("\n");
}
